### ISSUE TITLE
Bet with n possible outcomes and funds distributed proportinally

### ISSUE THREAD

**Issue by Ekliptor** [fyookball/ChainBet#5]
Is it possible to extend this protocol to a bet with n possible outcomes?
So instead of checking of Alice's and Bob's secrets A+B are an odd/even number, for n=11 it would check for example x = (A+B) MOD n:
x=0: all funds go to Bob (0/11 for Alice)
x=1: 9.09% funds go to Alice (1/11 for Alice)
...
x=10: 90% funds go to Alice (10/11 for Alice)

I know a client-side workaround would be to require n different funding transactions, but that would be
1. a usability nightmare (sending funds 11x from your wallet)
2. mathematically not the same type of bet, since this would be n times flipping a coin

Thanks

**Comment by fyookball** [comment]
https://github.com/fyookball/ChainBet/blob/master/DICE_ROLL.md
